#!/bin/bash'
sed -i {'s/[[:alpha:]]//g ; s/[[:blank:]]//g ; s/@/ at /g; s/";"/@/g; s/^"/#/g; s/"$/#/g;  s/"//g; s/@/";"/g;  s/#/"/g;  '}  K3241.K03200Y0.D30311.ESTABELE
sed -i {'s/[[:alpha:]]//g ; s/[[:blank:]]//g ; s/@/ at /g; s/";"/@/g; s/^"/#/g; s/"$/#/g;  s/"//g; s/@/";"/g;  s/#/"/g;  '}  'K3241.K03200Y1.D30311.ESTABELE'
sed -i {'s/[[:alpha:]]//g ; s/[[:blank:]]//g ; s/@/ at /g; s/";"/@/g; s/^"/#/g; s/"$/#/g;  s/"//g; s/@/";"/g;  s/#/"/g;  '}  'K3241.K03200Y2.D30311.ESTABELE'
sed -i {'s/[[:alpha:]]//g ; s/[[:blank:]]//g ; s/@/ at /g; s/";"/@/g; s/^"/#/g; s/"$/#/g;  s/"//g; s/@/";"/g;  s/#/"/g;  '}  'K3241.K03200Y3.D30311.ESTABELE'
sed -i {'s/[[:alpha:]]//g ; s/[[:blank:]]//g ; s/@/ at /g; s/";"/@/g; s/^"/#/g; s/"$/#/g;  s/"//g; s/@/";"/g;  s/#/"/g;  '}  'K3241.K03200Y4.D30311.ESTABELE'
sed -i {'s/[[:alpha:]]//g ; s/[[:blank:]]//g ; s/@/ at /g; s/";"/@/g; s/^"/#/g; s/"$/#/g;  s/"//g; s/@/";"/g;  s/#/"/g;  '}  'K3241.K03200Y5.D30311.ESTABELE'
sed -i {'s/[[:alpha:]]//g ; s/[[:blank:]]//g ; s/@/ at /g; s/";"/@/g; s/^"/#/g; s/"$/#/g;  s/"//g; s/@/";"/g;  s/#/"/g;  '}  'K3241.K03200Y6.D30311.ESTABELE'
sed -i {'s/[[:alpha:]]//g ; s/[[:blank:]]//g ; s/@/ at /g; s/";"/@/g; s/^"/#/g; s/"$/#/g;  s/"//g; s/@/";"/g;  s/#/"/g;  '}  'K3241.K03200Y7.D30311.ESTABELE'
sed -i {'s/[[:alpha:]]//g ; s/[[:blank:]]//g ; s/@/ at /g; s/";"/@/g; s/^"/#/g; s/"$/#/g;  s/"//g; s/@/";"/g;  s/#/"/g;  '}  'K3241.K03200Y8.D30311.ESTABELE'
sed -i {'s/[[:alpha:]]//g ; s/[[:blank:]]//g ; s/@/ at /g; s/";"/@/g; s/^"/#/g; s/"$/#/g;  s/"//g; s/@/";"/g;  s/#/"/g;  '}  'K3241.K03200Y9.D30311.ESTABELE'
